### ISSUE TITLE
This script can be used in mtDNA?

### ISSUE THREAD

**Issue by deyuanyang** [alondmnt/codon-bias#1]
Hi Alondmnt,

Thanks very much for sharing the nice script with us.

I have a small question， this script can be used in mtDNA?

Best wishes，
Deyuan

**Comment by alondmnt** [comment]
Hi @deyuanyang, any function in the package that has the `genetic_code` parameter can be used with any of the 33 genetic codes listed [here](https://en.wikipedia.org/wiki/List_of_genetic_codes) (using NCBI numbering). For example, vertebrate mitochondrial genes should be analyzed with `genetic_code=2` (see the full list for other mitochondria).
