### ISSUE TITLE
Codon or Codon Pair label for get_weights

### ISSUE THREAD

**Issue by zihian** [alondmnt/codon-bias#2]
get_weights() outputs an array of 61 codons or 3721 codonpairs. Is there a fixed order? If so, what is the order of codons/codonpairs?

**Comment by alondmnt** [comment]
the order is fixed: sorted by amino acids (AA), or amino acids pairs, and then synonymous codons for each AA.
maybe sorting by codons makes more sense in some cases.

anyway, the most explicit way to verify the order is to run the following code on a single sequence:
(this also works for single codon scores.)
```python
cb.scores.CodonPairBias(ref_seq=genes)._calc_seq_weights(genes[0])
```

you'll get something like this:
```text
GCAGCA    0.008180
GCAGCC    0.008180
GCAGCG   -0.008081
GCAGCT    0.008180
GCCGCA    0.008180
            ...   
TATTGG    0.000000
TACTAC    0.000000
TACTAT    0.000000
TATTAC    0.000000
TATTAT    0.000000
Name: log_ratio, Length: 3721, dtype: float64
```

**Comment by zihian** [comment]
This works for me. Thank you so much! Thank you also for writing this library
